'use strict';
// A design fixture, not an AI client. No network calls, credentials or persistent private data.
const $ = (selector) => document.querySelector(selector);
const sources = [
  {id:1, publisher:'W3C · Accessibility',title:'Make the mobile flow easy to tap',url:'https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html',claim:'WCAG 2.2 defines a minimum target size criterion and its exceptions. The proposed design uses larger, 44px primary touch controls.',limit:'This supports the interaction design. It does not establish member demand for an app.'},
  {id:2,publisher:'MDN Web Docs · Platform capability',title:'The web can support offline experiences',url:'https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API',claim:'Service workers can support offline experiences. That capability still needs an implementation and tests for the actual task and browser.',limit:'This does not prove that the proposed member flow works offline. No service worker is implemented in this prototype.'}
];
const fixture = [
 {role:'You',type:'owner',time:'10:40',body:'Do we need a mobile app for our member community, or can a better website do the job? We have a small team and most members visit on their phones.'},
 {role:'Head Consultant',type:'head',time:'10:40',body:'Let’s separate the member problem from the platform choice. Product, look at the main member journey. Operations, consider what the team can support. Critic, challenge the assumptions that could change the decision.'},
 {role:'Product Consultant',type:'product',time:'10:41',to:'Operations Consultant',body:'I’d start with the website. Members need to get from signing in to reading something useful without friction. Bigger touch controls and a clearer reading flow are worth testing first.',sources:[1]},
 {role:'Operations Consultant',type:'operations',time:'10:42',to:'Product Consultant',body:'Agreed on testing the journey. A separate app would add another release and support process. With this small team, I’d want evidence of a member need before taking that on.'},
 {role:'Critic',type:'critic',time:'10:43',to:'Product Consultant',quote:'I’d start with the website.',body:'That recommendation is incomplete if members need to read without a connection. Are we ruling out an app before we know where the website might fail them?'},
 {role:'Product Consultant',type:'product',time:'10:44',to:'Critic',body:'Fair challenge. The web can support offline experiences, but that doesn’t prove this one will work well. I’m changing the proposal: test one mobile reading journey and ask members when connectivity actually stops them. Keep the native-app decision open.',sources:[2]},
 {role:'Critic',type:'critic',time:'10:45',to:'Product Consultant',body:'That addresses my objection. I support a limited test, with a clear condition: if an essential offline task still fails, revisit the platform choice. We have a recommendation to test, not proof that a native app is unnecessary.'},
 {role:'Head Consultant',type:'head',time:'10:46',body:'Start with one improved mobile web journey. Test it with members before funding another product. The unresolved question is how much offline reading matters.',outcome:true}
];
let currentView='discussion', currentState='discussion', timer=null, toastTimer=null, shown=fixture.length, attachments=[], draft='', selectedSpeed='Balanced', loginConsent=false, deleted=false;
const escapeHtml = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,6500);}
function messageMarkup(m){return `<article class="message ${m.type==='owner'?'user':''} ${m.type==='critic'?'critic-message':''}" aria-label="${escapeHtml(m.role)}${m.to?' to '+escapeHtml(m.to):''}"><span class="avatar ${m.type}" aria-hidden="true">${m.type==='owner'?'Y':m.role[0]}</span><div><div class="message-head"><strong>${escapeHtml(m.role)}</strong>${m.to?`<span class="recipient">→ ${escapeHtml(m.to)}</span>`:''}<time>${m.time}</time></div><div class="message-body">${m.quote?`<blockquote>${escapeHtml(m.quote)}</blockquote>`:''}<p>${escapeHtml(m.body)}</p>${(m.sources||[]).map(id=>`<button class="citation" data-source="${id}">${id} · ${id===1?'W3C':'MDN'} <span aria-hidden="true">↗</span></button>`).join('')}${m.outcome?'<div class="inline-outcome"><p><strong>The next move:</strong> test one complete member journey.</p><button data-action="outcome">Read the three-step plan <span aria-hidden="true">↗</span></button></div>':''}</div></div></article>`;}
function sourceMarkup(s){return `<article class="source-card"><div class="source-meta"><span>${s.id.toString().padStart(2,'0')}</span><span>${escapeHtml(s.publisher)}</span></div><h3>${escapeHtml(s.title)}</h3><p>${escapeHtml(s.claim)}</p><p><strong>Limit:</strong> ${escapeHtml(s.limit)}</p><a href="${s.url}" target="_blank" rel="noopener noreferrer">Open reference <span aria-hidden="true"> ↗</span></a></article>`;}
function renderThread(){ $('#thread').innerHTML=fixture.slice(0,shown).map(messageMarkup).join('');$('#tab-discussion span').textContent=String(shown); }
function showView(view,moveFocus=false){currentView=view;document.querySelectorAll('[data-view]').forEach(b=>{const active=b.dataset.view===view;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;});['discussion','outcome','sources'].forEach(x=>$('#panel-'+x).hidden=x!==view);if(moveFocus)$('#tab-'+view).focus();}
function cancelPlayback(){clearTimeout(timer);timer=null;$('#stop').hidden=true;$('#replay').hidden=false;}
function setState(state){cancelPlayback();currentState=state;$('#replay').textContent='Replay discussion ↻';$('#replay').dataset.action='replay';$('#preview-state').value=state;const login=state==='login',empty=state==='new';$('#login').hidden=!login;$('#app-shell').hidden=login;$('#empty-state').hidden=!empty;$('#conversation-heading').hidden=empty;$('#view-tabs').hidden=empty;$('#content-grid').hidden=empty;$('#notice').hidden=true;$('#message').value=draft;$('#message').placeholder=empty?'Describe your situation…':'Add context or ask a follow-up…';$('#draft-status').textContent='Sample only · No message will be sent';$('#session-status').textContent='Reviewed · One assumption to test';shown=fixture.length;renderThread();showView('discussion');$('#playback-status').textContent='Example conversation · 10:40–10:46';
 const notices={offline:['You’re offline. Your draft is still here.','The saved conversation will catch up when you reconnect.','Try again','recover'],auth:['ChatGPT needs you to sign in again.','Your conversation and draft are preserved.','Reconnect ChatGPT','reconnect'],quota:['ChatGPT’s usage limit has been reached.','Reset time is unavailable. Your conversation is preserved.','Check again','recover'],research:['The source could not be checked.','The conclusion stays provisional until this claim is verified.','Retry research','recover']};
 if(notices[state]){let [title,desc,label,action]=notices[state];$('#notice').innerHTML=`<div><strong>${title}</strong><small>${desc}</small></div><button data-action="${action}">${label}</button>`;$('#notice').hidden=false;$('#session-status').textContent=state==='research'?'Provisional · Source unverified':'Paused · Conversation preserved';}
 if(empty){$('#message').focus();}window.scrollTo({top:0,behavior:'instant'});
}
function showDialog(title,body){$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=body;$('#dialog').showModal();$('#dialog').querySelector('button').focus();}
function closeDialog(){ $('#dialog').close(); }
function showPreferences(){showDialog('Your preferences',`<p class="dialog-copy">Your current conversation keeps the settings it started with.</p><div class="preference-group"><h3>Head & specialists</h3><strong>GPT-6 Astra</strong><p>Codex · Extra high reasoning <code>xhigh</code></p></div><div class="preference-group"><h3>Critic</h3><strong>GPT-6 Astra</strong><p>Codex · Ultra reasoning <code>ultra</code></p></div><div class="preference-group"><label for="speed">Conversation pace<select id="speed"><option${selectedSpeed==='Fast'?' selected':''}>Fast</option><option${selectedSpeed==='Balanced'?' selected':''}>Balanced</option><option${selectedSpeed==='Thorough'?' selected':''}>Thorough</option></select></label></div><p class="privacy-line">Prototype model values reflect the 7 September record, not a live settings read. The full provider/model controls will use the verified catalog during implementation.</p><div class="dialog-actions"><button class="text-button" data-action="signout">Sign out</button><button class="primary" data-action="save-preferences">Save preferences</button></div>`);}
function renderAttachments(){ $('#attachment-list').innerHTML=attachments.map((f,i)=>`<button type="button" data-remove-attachment="${i}" aria-label="Remove ${escapeHtml(f.name)}">${escapeHtml(f.name)} ×</button>`).join(''); }
function exportExample(){const text='# Design prototype — fictional example\n\nNo live consultation or current research is represented.\n\n'+fixture.map(m=>`## ${m.role}${m.to?' → '+m.to:''}\n\n${m.body}`).join('\n\n')+'\n\n## Reference links\n'+sources.map(s=>`- ${s.title}: ${s.url}`).join('\n');const url=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='consulting-group-example.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Fictional example exported. Your draft was not included.');}
const actions={
 new(){draft=$('#message').value;setState('new');},
 example(){deleted=false;document.querySelector('.sidebar .history-item').hidden=false;draft=$('#message').value;setState('discussion');},
 history(){showDialog('Conversations',`<button class="new-button" data-action="dialog-new">＋ New conversation</button>${deleted?'<p class="dialog-copy">No saved conversations in this preview.</p>':'<button class="history-item selected" data-action="dialog-example"><span class="history-dot"></span><span>A better mobile experience<small>Fictional example · Today</small></span></button>'}`);},
 'dialog-new'(){closeDialog();actions.new();},'dialog-example'(){closeDialog();actions.example();},
 account:showPreferences,
 options(){showDialog('Conversation',`<div class="dialog-menu"><button data-action="dialog-new">New conversation</button><button data-action="account">Preferences</button><button data-action="export">Export example</button><button class="danger" data-action="delete">Delete example conversation</button><button data-action="signout">Sign out</button></div>`);},
 outcome(){showView('outcome');$('#view-tabs').scrollIntoView({block:'start'});},
 sources(){showView('sources');$('#view-tabs').scrollIntoView({block:'start'});},
 followup(){showView('discussion');$('#message').value='How should we structure the member test?';draft=$('#message').value;$('#message').focus();},
 close:closeDialog,
 login(){if(loginConsent){setState('new');return;}showDialog('Before we begin',`<p class="dialog-copy">Your selected AI providers process the content you choose to share. Conversations are private to your account and retained until you delete them.</p><p class="dialog-copy">Keep passwords and sensitive records out of the conversation. Public-web research uses minimized queries.</p><label class="consent"><input id="processing-consent" type="checkbox"> <span>I agree to this processing for my conversations.</span></label><p class="privacy-line">Prototype consent only. Nothing is transmitted.</p><button class="primary" id="start-conversation" data-action="consent" disabled>Open my workspace</button>`);},
 consent(){if(!$('#processing-consent')?.checked)return;loginConsent=true;closeDialog();setState('new');},
 signout(){if($('#dialog').open)closeDialog();cancelPlayback();draft='';attachments=[];$('#message').value='';renderAttachments();setState('login');},
 attach(){$('#attachment').click();},
 'save-preferences'(){selectedSpeed=$('#speed').value;closeDialog();toast(`${selectedSpeed} saved for the next example. Current conversation unchanged.`);},
 export:exportExample,
 delete(){showDialog('Delete this conversation?',`<p class="dialog-copy">The example will be removed from this preview. No server data exists here.</p><div class="dialog-actions"><button class="text-button" data-action="close">Keep conversation</button><button class="primary" data-action="confirm-delete">Delete example</button></div>`);},
 'confirm-delete'(){deleted=true;document.querySelector('.sidebar .history-item').hidden=true;draft='';attachments=[];renderAttachments();closeDialog();setState('new');toast('Example removed from this preview.');},
 recover(){const prior=currentState;setState('discussion');toast(`Preview recovery complete (${prior}). No service was contacted.`);},
 reconnect(){showDialog('Reconnect ChatGPT',`<p class="dialog-copy">In the live product, this opens the selected provider’s sign-in flow and returns to your paused consultation.</p><p class="dialog-copy">This preview does not open or grant provider access.</p><div class="dialog-actions"><button class="text-button" data-action="close">Back to conversation</button><button class="primary" data-action="demo-reconnected">Preview successful return</button></div>`);},
 'demo-reconnected'(){closeDialog();setState('discussion');toast('Preview only: returned to the preserved conversation.');},
 replay(){cancelPlayback();showView('discussion');shown=1;renderThread();$('#stop').hidden=false;$('#replay').hidden=true;$('#session-status').textContent='Playing example · No live agents';$('#playback-status').textContent='Scripted example playback';const next=()=>{shown++;renderThread();if(shown<fixture.length){timer=setTimeout(next,1200);}else{cancelPlayback();$('#session-status').textContent='Reviewed · One assumption to test';$('#playback-status').textContent='Example playback complete';}};timer=setTimeout(next,1200);},
 stop(){cancelPlayback();$('#session-status').textContent='Stopped · Example preserved';$('#playback-status').textContent=`Paused after ${shown} example messages`;$('#replay').textContent='Continue example';$('#replay').dataset.action='continue';},
 continue(){const from=shown;actions.replay();shown=from;renderThread();$('#replay').textContent='Replay discussion ↻';$('#replay').dataset.action='replay';}
};
document.addEventListener('click',e=>{const btn=e.target.closest('[data-action]');if(btn){const fn=actions[btn.dataset.action];if(fn)fn();}const source=e.target.closest('[data-source]');if(source){const s=sources.find(x=>x.id===Number(source.dataset.source));showDialog('Source detail',sourceMarkup(s));}const remove=e.target.closest('[data-remove-attachment]');if(remove){attachments.splice(Number(remove.dataset.removeAttachment),1);renderAttachments();}});
$('#preview-state').addEventListener('change',e=>{draft=$('#message').value;setState(e.target.value);});
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>showView(button.dataset.view)));
$('#view-tabs').addEventListener('keydown',e=>{const names=['discussion','outcome','sources'];let index=names.indexOf(currentView);if(e.key==='ArrowRight')index=(index+1)%3;else if(e.key==='ArrowLeft')index=(index+2)%3;else if(e.key==='Home')index=0;else if(e.key==='End')index=2;else return;e.preventDefault();showView(names[index],true);});
$('#message').addEventListener('input',()=>{draft=$('#message').value;$('#draft-status').textContent=draft?'Draft stays in this tab · Not sent':'Sample only · No message will be sent';});
$('#composer-form').addEventListener('submit',e=>{e.preventDefault();draft=$('#message').value;if(!draft.trim()&&!attachments.length){$('#message').focus();toast('Write a message or choose an attachment first.');return;}$('#draft-status').textContent='Draft saved in this tab · No AI call';toast('Draft kept in this tab. Use the sample discussion to preview consultant replies.');});
$('#attachment').addEventListener('change',e=>{let rejected=false;for(const f of e.target.files){if(!['image/png','image/jpeg','image/webp','application/pdf'].includes(f.type)||f.size>20*1024*1024){rejected=true;continue;}attachments.push({name:f.name});}renderAttachments();e.target.value='';toast(rejected?'Choose a PNG, JPEG, WebP or PDF up to 20 MB. Accepted filenames stay in this tab.':'Filenames added to this preview. No file content is read or uploaded.');});
document.addEventListener('change',e=>{if(e.target.id==='processing-consent')$('#start-conversation').disabled=!e.target.checked;});
$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog')){const r=$('#dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
window.addEventListener('hashchange',()=>{if(location.hash==='#discussion')setState('discussion');});
$('#sources-list').innerHTML=sources.map(sourceMarkup).join('');
setState('discussion');
